CREATE TABLE Expense_Parent (
ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT UNIQUE,
Name VARCHAR(255) NOT NULL UNIQUE);

CREATE TABLE Accounts (
ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT UNIQUE,
Name VARCHAR(255) NOT NULL);

CREATE TABLE State (
ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT UNIQUE);

CREATE TABLE Expenses (
ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT UNIQUE,
Name VARCHAR(255) NOT NULL,
Frequency_Code VARCHAR(255),
Account_Id INT NOT NULL,
Parent_Id INT NOT NULL,
Amount FLOAT NOT NULL,
Date_Taken VARCHAR(255),
FOREIGN KEY (Account_Id) REFERENCES Accounts(ID),
FOREIGN KEY (Parent_Id) REFERENCES Expense_Parent(ID)
);

CREATE TABLE Week (
ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT UNIQUE,
Week_Begin DATE NOT NULL UNIQUE,
State_Id INT NOT NULL,
FOREIGN KEY (State_Id) REFERENCES State(ID));

CREATE TABLE State_Expense (
Expense_Id INT NOT NULL,
State_Id INT NOT NULL,
FOREIGN KEY (State_Id) REFERENCES State(ID),
FOREIGN KEY (Expense_Id) REFERENCES Expenses(ID)
);

CREATE TABLE Week_Expense (
Expense_Id INT NOT NULL,
Week_Id INT NOT NULL,
Amount FLOAT NOT NULL,
FOREIGN KEY (Expense_Id) REFERENCES Expenses(ID),
FOREIGN KEY (Week_Id) REFERENCES Week(ID));

CREATE TABLE Week_Account (
Account_Id INT NOT NULL,
Week_Id INT NOT NULL,
Account_Amount FLOAT,
Account_Overspend FLOAT,
FOREIGN KEY (Week_Id) REFERENCES Week(ID),
FOREIGN KEY (Account_Id) REFERENCES Incomes(ID));